version: "3"

services:
  # Service pour le frontend
  frontend:
    build:
      dockerfile: ./apps/frontend/Dockerfile.prod
    environment:
      - PORT=3000
      - NODE_ENV=production
      - VIRTUAL_HOST=hi.snowledge.eu
      - LETSENCRYPT_HOST=hi.snowledge.eu
      - LETSENCRYPT_EMAIL=alexandre@snowledge.eu
      - VIRTUAL_PORT=3000
  # Service pour le backend
  backend:
    build:
      dockerfile: ./apps/backend/Dockerfile.prod
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - snowledge_network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=alexandre@snowledge.eu
    volumes:
      - ./certs:/etc/nginx/certs
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - snowledge_network

networks:
  snowledge_network:
    external: true
