version: "3"

services:
  # Service pour le frontend
  frontend:
    environment:
      - NODE_ENV=production
  # Service pour le backend
  backend:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snowledge